name: Deploy
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        run: mvn clean install &&
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}
          mvn clean heroku:deploy
      - name: End-to-end tests
        run: npm install -g newman &&
          newman run resources/postman_collection.e2e_tests.json --environment resources/postman_environment.json
