name: Deploy
on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        run: mvn clean install &&
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}
          mvn clean heroku:deploy
      - uses: matt-ball/newman-action@master
      - name: Integration tests
         with:
           collection: resources/postman_collection.integration_tests.json
           environment: resources/postman_environment.json
