name: E2E Tests

on:
  workflow_run:
    workflows:
      - Deploy
    types:
      - completed
    branches:
      - develop

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: End-to-end tests
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install -g newman
      - run: newman run resources/postman_collection.e2e_tests.json --environment resources/postman_environment.json
